### ISSUE TITLE
server 500 everywhere

### ISSUE THREAD

**Issue by bonds-git** [upsonp/dart#117]
OK, other than the documentation button all the buttons on the mission level return a Server 500 error, at a glance it looks as if I'm missing some table in the sql lite backend???

"Updating Application"
warning: redirecting to https://github.com/upsonp/dart/
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 38 (delta 30), reused 36 (delta 29), pack-reused 0
Unpacking objects: 100% (38/38), 5.39 KiB | 33.00 KiB/s, done.
From http://github.com/upsonp/dart
 * branch            master     -> FETCH_HEAD
   7a8298c..5063070  master     -> origin/master
Requirement already satisfied: pip in c:\dfo-mpo\dart\dart_env\lib\site-packages (23.2)
"Checking if update required"
"Updating Python Libraries, this may take several minutes"
"Collecting static files, this may take a moment"
Found another file with the destination path 'bootstrap_datepicker_plus\css\datepicker-widget.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'bootstrap_datepicker_plus\js\datepicker-widget.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

1 static file copied to 'C:\DFO-MPO\dart\staticfiles', 14879 unmodified.
"Creating/Updating local database"
Traceback (most recent call last):
  File "C:\DFO-MPO\dart\manage.py", line 22, in <module>
    main()
  File "C:\DFO-MPO\dart\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\migrations\loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration phyto.0001_initial is applied before its dependency core.0015_auto_20230622_1010 on database 'default'.
Traceback (most recent call last):
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: bio_tables_bcdatacenter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DFO-MPO\dart\manage.py", line 22, in <module>
    main()
  File "C:\DFO-MPO\dart\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\serializers\base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\sql\compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture 'C:\DFO-MPO\dart\bio_tables\fixtures\biochem_fixtures.json': Could not load bio_tables.BCDataCenter(pk=10): no such table: bio_tables_bcdatacenter
Traceback (most recent call last):
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_geographicregion

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DFO-MPO\dart\manage.py", line 22, in <module>
    main()
  File "C:\DFO-MPO\dart\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\management\commands\loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\core\serializers\base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\sql\compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\DFO-MPO\dart\dart_env\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture 'C:\DFO-MPO\dart\core\fixtures\geographic_region.json': Could not load core.GeographicRegion(pk=1): no such table: core_geographicregion
"Starting webserver: http://localhost:8000/"
2023-07-20 07:06:57,448 INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2023-07-20 07:06:57,448 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2023-07-20 07:06:57,448 INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2023-07-20 07:06:57,455 INFO     Listening on TCP address 127.0.0.1:8000

**Comment by upsonp** [comment]
Bummer. I was hoping that wouldn't be an issue for you.

I was doing some work on the Phytoplankton awhile ago, but it turns out I mixed up Phyto and Zoo plankton. I ended up fixing the issue, but the part of the code that builds the phytoplankton tables was in the GitHub repo and got overridden when I fixed the issue (much later on).

Django can't figure out what to do with the conflicting phyto.0001_initial migration because your version of the DB was built with the old version of the phyto.0001_initial file so it's out of sequence with the rest of the code. And because it's out of sequence Django can't add any of the new tables.

I'm going to see if I can track down the version of the phyto.0001_initial that your DB was likely built from and see if I can't fix the migration.
